name: Terraform with Manual Token

on:
  workflow_dispatch:  # Manual trigger only (no automatic runs)

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_ACCESS_TOKEN: ${{ secrets.ARM_ACCESS_TOKEN }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.1

      - name: Terraform Init
        working-directory: Exo_Terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: Exo_Terraform
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: Exo_Terraform
        run: terraform apply -auto-approve
